# permissions for end users to view serviceimports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceimport-viewer-role
rules:
- apiGroups:
  - networking.kubeslice.io
  resources:
  - serviceimports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.kubeslice.io
  resources:
  - serviceimports/status
  verbs:
  - get
