name: learn-github-actions
on: [push]
jobs:
  end-to-end-test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Clone the repository
        uses: actions/checkout@v3
      -
        name: setup the node version
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
